Update ts-sidecar-iperf.yaml to set replicas to 200, re-enabling the StatefulSet deployment and enhancing scalability for Tailscale examples.

diff --git a/clusters/common/apps/tailscale-examples/sandbox/sidecar/ts-sidecar-iperf.yaml b/clusters/common/apps/tailscale-examples/sandbox/sidecar/ts-sidecar-iperf.yaml
--- a/clusters/common/apps/tailscale-examples/sandbox/sidecar/ts-sidecar-iperf.yaml
+++ b/clusters/common/apps/tailscale-examples/sandbox/sidecar/ts-sidecar-iperf.yaml
@@ -1,93 +1,93 @@
-# apiVersion: apps/v1
-# kind: StatefulSet
-# metadata:
-#   name: ${LOCATION}-sidecar-iperf
-# spec:
-#   replicas: 0
-#   serviceName: ${LOCATION}-sidecar-iperf
-#   podManagementPolicy: Parallel
-#   updateStrategy:
-#     type: RollingUpdate
-#   selector:
-#     matchLabels:
-#       app: ${LOCATION}-sidecar-iperf
-#   template:
-#     metadata:
-#       labels:
-#         app: ${LOCATION}-sidecar-iperf
-#     spec:
-#       serviceAccountName: "tailscale"
-#       initContainers:
-#       - args:
-#         - sysctl -w net.ipv4.ip_forward=1 && if sysctl net.ipv6.conf.all.forwarding;
-#           then sysctl -w net.ipv6.conf.all.forwarding=1; fi
-#         command:
-#         - /bin/sh
-#         - -c
-#         image: "ghcr.io/tailscale/tailscale:latest"
-#         # imagePullPolicy: Always
-#         name: sysctler
-#         securityContext:
-#           privileged: true
-#       containers:
-#       - name: iperf-server
-#         image: nicolaka/netshoot:latest
-#         command: ["/bin/sh", "-c", "iperf3 -s"]
-#       - name: iperf-client
-#         image: nicolaka/netshoot:latest
-#         command:
-#         - /bin/sh
-#         - -c
-#         - |
-#           set +e
-#           TARGET_HOST=$(echo $POD_NAME | sed "s/${LOCATION}/${FAILOVER}/")
-#           echo "Will continuously test to $TARGET_HOST"
-#           while true; do
-#             echo "[$(date)] Connecting to $TARGET_HOST..."
-#             iperf3 -c $TARGET_HOST -t 300 2>&1 || echo "Connection failed, retrying..."
-#           done
-#         env:
-#         - name: POD_NAME
-#           valueFrom:
-#             fieldRef:
-#               fieldPath: metadata.name
-#         - name: LOCATION
-#           value: "${LOCATION}"
-#         - name: FAILOVER
-#           value: "${FAILOVER}"
-#       - name: tailscale
-#         # imagePullPolicy: Always
-#         image: "ghcr.io/tailscale/tailscale:latest"
-#         securityContext:
-#           privileged: true
-#         env:
-#         - name: TS_KUBE_SECRET
-#           value: ""
-#         - name: TS_USERSPACE
-#           value: "false"
-#         - name: TS_STATE_DIR
-#           value: "/dev/shm"
-#         - name: TS_DEBUG_FIREWALL_MODE
-#           value: auto
-#         - name: TS_AUTHKEY
-#           valueFrom:
-#             secretKeyRef:
-#               name: ts-oauth
-#               key: TS_AUTHKEY_EPHEMERAL
-#               optional: true
-#         - name: TS_ACCEPT_DNS
-#           value: "true"
-#         - name: TS_EXTRA_ARGS
-#           value: "--advertise-tags=tag:k8s,tag:${LOCATION} --accept-routes --ssh"
-#         - name: POD_NAME
-#           valueFrom:
-#             fieldRef:
-#               fieldPath: metadata.name
-#         - name: TS_HOSTNAME
-#           valueFrom:
-#             fieldRef:
-#               fieldPath: metadata.name
-#         - name: POD_UID
-#           valueFrom:
-#             fieldRef:
-#               fieldPath: metadata.uid
+apiVersion: apps/v1
+kind: StatefulSet
+metadata:
+  name: ${LOCATION}-sidecar-iperf
+spec:
+  replicas: 200
+  serviceName: ${LOCATION}-sidecar-iperf
+  podManagementPolicy: Parallel
+  updateStrategy:
+    type: RollingUpdate
+  selector:
+    matchLabels:
+      app: ${LOCATION}-sidecar-iperf
+  template:
+    metadata:
+      labels:
+        app: ${LOCATION}-sidecar-iperf
+    spec:
+      serviceAccountName: "tailscale"
+      initContainers:
+      - args:
+        - sysctl -w net.ipv4.ip_forward=1 && if sysctl net.ipv6.conf.all.forwarding;
+          then sysctl -w net.ipv6.conf.all.forwarding=1; fi
+        command:
+        - /bin/sh
+        - -c
+        image: "ghcr.io/tailscale/tailscale:latest"
+        # imagePullPolicy: Always
+        name: sysctler
+        securityContext:
+          privileged: true
+      containers:
+      - name: iperf-server
+        image: nicolaka/netshoot:latest
+        command: ["/bin/sh", "-c", "iperf3 -s"]
+      - name: iperf-client
+        image: nicolaka/netshoot:latest
+        command:
+        - /bin/sh
+        - -c
+        - |
+          set +e
+          TARGET_HOST=$(echo $POD_NAME | sed "s/${LOCATION}/${FAILOVER}/")
+          echo "Will continuously test to $TARGET_HOST"
+          while true; do
+            echo "[$(date)] Connecting to $TARGET_HOST..."
+            iperf3 -c $TARGET_HOST -t 300 2>&1 || echo "Connection failed, retrying..."
+          done
+        env:
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        - name: LOCATION
+          value: "${LOCATION}"
+        - name: FAILOVER
+          value: "${FAILOVER}"
+      - name: tailscale
+        # imagePullPolicy: Always
+        image: "ghcr.io/tailscale/tailscale:latest"
+        securityContext:
+          privileged: true
+        env:
+        - name: TS_KUBE_SECRET
+          value: ""
+        - name: TS_USERSPACE
+          value: "false"
+        - name: TS_STATE_DIR
+          value: "/dev/shm"
+        - name: TS_DEBUG_FIREWALL_MODE
+          value: auto
+        - name: TS_AUTHKEY
+          valueFrom:
+            secretKeyRef:
+              name: ts-oauth
+              key: TS_AUTHKEY_EPHEMERAL
+              optional: true
+        - name: TS_ACCEPT_DNS
+          value: "true"
+        - name: TS_EXTRA_ARGS
+          value: "--advertise-tags=tag:k8s,tag:${LOCATION} --accept-routes --ssh"
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        - name: TS_HOSTNAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        - name: POD_UID
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.uid
